apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-selfsigned-issuer
  namespace: linkerd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-trust-anchor-secret
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: linkerd-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor-issuer
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor-secret
