apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-tls
  namespace: online-boutique
spec:
  secretName: frontend-tls-secret
  duration: 24h
  renewBefore: 12h
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: frontend.online-boutique.svc.cluster.local
  dnsNames:
  - frontend.online-boutique.svc.cluster.local
  usages:
  - "server auth"
  - "client auth"
