apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-portal
  namespace: docs-portal
  labels:
    app: docs-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docs-portal
  template:
    metadata:
      labels:
        app: docs-portal
        sre-privileged-access: "true"
    spec:
      containers:
      - name: docs-portal
        image: nginxinc/nginx-unprivileged:alpine
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: docs-portal
  namespace: docs-portal
spec:
  selector:
    app: docs-portal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
