apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fbscotta369/ai4all-sre.git'
    path: gitops/argo-apps/docs-portal
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docs-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
